apiVersion: apps/v1
kind: Deployment
metadata: 
  name: first-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      page: web-page
  template:
    metadata:
      labels:
        page: web-page
    spec:
      containers:
        - name: web-page-with-port
          image:  nithishreddy305/porting-webpage:v1
          ports:
          - containerPort:  90